### ISSUE TITLE
Error when uploading an Excel file to the platform. 

### ISSUE THREAD

**Issue by eduardocorrearaujo** [thegraphnetwork/EpiGraphHub#110]
I tried to upload an Excel file to the platform and receive this error message: 
<img width="897" alt="Captura de Tela 2022-06-02 às 11 02 44" src="https://user-images.githubusercontent.com/65051489/171647144-d9de753d-67fc-4baa-859b-c7c536690131.png">

**Comment by xmnlab** [comment]
fixed on production. for now, production is using the branch #103 
it should be merged on main very soon.
