### ISSUE TITLE
[DATASET] Brazilian SUS data

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#123]
## Dataset description

The Brazilian "Sistema Unico de Saúde" has very complete datasets going back to the late 20th century.
This issue is to guide the development of regular collection of their datasets.

## Available API

We will use the Python library PySUS to access the open datasets. We will start with SINAN data, the disease surveillance database.
https://pysus.readthedocs.io/en/latest/SINAN.html

## More info
The code to download the files and inserting in the database should be done using the Airflow framework

**Comment by esloch** [comment]
[Done!](https://github.com/thegraphnetwork/epigraphhub_py/pull/179)
