### ISSUE TITLE
Feature: deploy Jupyterlite using Github pages

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#136]
Jupyterlite is a jupyter notebook server running on webassemply through pyodide.

We can benefit from having our own jupyterlite [running as a github page](https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html) so that users can play with with epigraphhub examples code.

**Comment by xmnlab** [comment]
sounds interesting . I will take a look into that!

**Comment by xmnlab** [comment]
I need to check if all the dependencies would be available for wasm 
another option is to use mybinder

**Comment by xmnlab** [comment]
looks very nice .. I will play a bit with that today :)

**Comment by fccoelho** [comment]
I have done a deploy on my [github pages](https://fccoelho.github.io/jupyterlite), but it is still quite limited in what libraries it can install. so maybe we can wait for it to mature a lot more.

**Comment by xmnlab** [comment]
Got it. Do you want me to work on the mybinder for epigrphhub?

**Comment by fccoelho** [comment]
Honestly, I think we should go for something more scalable, that can also serve our external analysts for real work not to just browse documentation examples. If we're going to invest on this, perhaps we should look into [deploying jupyterhub](https://jupyterhub.readthedocs.io/en/stable/getting-started/institutional-faq.html).

**Comment by xmnlab** [comment]
That would be great. Maybe we could try qhub?

**Comment by fccoelho** [comment]
Yes, let's do a test deploy for QHub. Closing this issue.
