### ISSUE TITLE
Create an Airflow DAG to Check Project services

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#137]
Create a simple DAG that will scan through the list of Web services of our platform to see if they are Up and responding accordigly. if the acess fails, it should send an email to admin@epgraphhub.org

This list should reside on a file (for example, `services.txt` ) on this repo that the dag can read from. In this way when we add a new webservice, we just have to edit that file:
### Initial content of services.txt

- https://epigraphhub.org
- https://www.epigraphhub.org
- https://dash.epigraphhub.org
- https://epigraphhub.org/covidch
- https://airflow.epigraphhub.org

The implementation could make use of urllib:
```python
In [1]: from urllib.request import urlopen

In [2]: resp = urlopen("https://epigraphhub.org")

In [3]: resp
Out[3]: <http.client.HTTPResponse at 0x7fac25548430>

In [4]: resp.code
Out[4]: 200
```
If the response code is `2**`, all is fine, if not. Send email with the Error code.

**Comment by luabida** [comment]
I've created a separate branch to include all sort of tests using Airflow that will be merged into #133. 

Request testing results (https://epigraphhub.org/covidch has returned an error as expected):
![image](https://user-images.githubusercontent.com/82233055/192346030-603c83e5-4285-4616-b59e-59fb14e98d49.png)


https://github.com/luabida/EpiGraphHub/pull/1
