### ISSUE TITLE
[BUG] Swiss COVID dashboard is offline

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#139]
### Describe the bug

The dashboard website is offline

### To Reproduce

go to https://epigraphhub.org/covidch

### Expected behavior

live dashboard

### Screenshots

na

### Desktop

- Device
- OS:
- Browser:
- Version:

### Smartphone

- OS:
- Browser:
- Version:

**Comment by xmnlab** [comment]
fixed.

the services was not running.
