### ISSUE TITLE
Use EpiGraphHub nightly from opensciencelabs conda channel

### ISSUE THREAD

**Issue by xmnlab** [thegraphnetwork/EpiGraphHub#140]
Now that the superset nightly conda package is ready, it would be good to update the epigraphhub.

Steps: 

- https://github.com/thegraphnetwork/EpiGraphHub/blob/main/conda/prod.yaml#L23 change from `superset 2.0.0` to `opensciencelabs::superset >=2.0.0`
- comment these two lines: https://github.com/thegraphnetwork/EpiGraphHub/blob/main/conda/prod.yaml#L52-L53
- run `make conda-lock`
- uncomment back these two lines: https://github.com/thegraphnetwork/EpiGraphHub/blob/main/conda/prod.yaml#L52-L53

**Comment by xmnlab** [comment]
we needed to move back to version 1.5

we have now a new version here https://github.com/osl-package-recipes/superset-feedstock-nightly
we should try it again. I will reopen this issue

**Comment by xmnlab** [comment]
@fccoelho it seems it has some issues yet: https://github.com/apache/superset/issues/23478
let's wait for some answers there :) 
hopefully there is some way to workaround that .. or maybe it is just a problem with "--version "

**Comment by fccoelho** [comment]
Agree...
