### ISSUE TITLE
[BUG] Missing env variables in Airflow Container to be able to mailing on errors

### ISSUE THREAD

**Issue by luabida** [thegraphnetwork/EpiGraphHub#172]
### Describe the bug

```
[2023-03-15, 15:36:56 UTC] {{configuration.py:552}} WARNING - section/key [smtp/smtp_user] not found in config
[2023-03-15, 15:36:56 UTC] {{email.py:228}} INFO - Email alerting: attempt 1
[2023-03-15, 15:36:56 UTC] {{configuration.py:552}} WARNING - section/key [smtp/smtp_user] not found in config
[2023-03-15, 15:36:56 UTC] {{email.py:228}} INFO - Email alerting: attempt 1
[2023-03-15, 15:36:56 UTC] {{taskinstance.py:1964}} ERROR - Failed to send email to: ['epigraphhub@thegraphnetwork.org']
```

### Variables that should be added:

`AIRFLOW__SMTP__SMTP_HOST`: The SMTP server hostname or IP address.
`AIRFLOW__SMTP__SMTP_PORT`: The SMTP server port number.
`AIRFLOW__SMTP__SMTP_STARTTLS`: (Optional) Set this to True if your SMTP server requires a secure connection using STARTTLS.
`AIRFLOW__SMTP__SMTP_SSL`: (Optional) Set this to True if your SMTP server requires a secure connection using SSL.
`AIRFLOW__SMTP__SMTP_USER`: The username for authenticating with the SMTP server.
`AIRFLOW__SMTP__SMTP_PASSWORD`: The password for authenticating with the SMTP server.
`AIRFLOW__SMTP__SMTP_MAIL_FROM`: The email address that will be used as the sender for all emails sent by Airflow.
`AIRFLOW__SMTP__SMTP_TLS`: (Optional) Set this to True if you want to use a secure connection using TLS.

### To Reproduce

https://airflow.epigraphhub.org/log?dag_id=SINAN_SIFG&task_id=upload&execution_date=2023-02-01T00%3A00%3A00%2B00%3A00

### Expected behavior

Sending the email

### Screenshots

![image](https://user-images.githubusercontent.com/82233055/225610492-5f396c7d-b932-4f4c-a0ae-8df0288d1e58.png)

### Desktop

- Device
- OS:
- Browser:
- Version:

### Smartphone

- OS:
- Browser:
- Version:

**Comment by xmnlab** [comment]
btw, for requests about production, please open a PR on https://github.com/thegraphnetwork/epigraphhub-deployment
