### ISSUE TITLE
Avoid reporting delay in the training of the models

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#23]
We have determined that the delay in reporting for the cases is <=3 for most cases, thus to avoid the underprediction bias in the forecast, we should use for the forecast, the predictors without the last three points `[:-3]`.

**Comment by dcpcamara** [comment]
Thanks, I'll make sure to add this into the Epinow script.

---------
*Daniel C. P. Câmara, PhD.*

*Laboratório de Mosquitos Transmissores de Hematozoários - LATHEMA, Fiocruz*
*Núcleo** Operacional Sentinela de Mosquitos Vetores - NOSMOVE, Fiocruz*
*Incident Management Support Team - IMST, WHO Afro*

*The GRAPH Network, UNIGE*
*Rio de Janeiro, Brasil*


Em sex., 14 de jan. de 2022 às 07:45, Flávio Codeço Coelho <
***@***.***> escreveu:

**Comment by eduardocorrearaujo** [comment]
Ok
