### ISSUE TITLE
move make_forecast.py to epigraphhub_py

### ISSUE THREAD

**Issue by xmnlab** [thegraphnetwork/EpiGraphHub#24]
from @fccoelho 

> The code on `make_forecast.py` Should be eventually moved into the [epigraphhub python library](https://github.com/thegraphnetwork/epigraphhub_py) and could have it's own tests and CI within that package. The here we would just maintain forecast.sh and perhaps mock the running of the forecast models somehow.

**Comment by eduardocorrearaujo** [comment]
It's done in PR #165 on epigraphhub_py.
