### ISSUE TITLE
[performance] forecast.sh takes too long to be executed

### ISSUE THREAD

**Issue by xmnlab** [thegraphnetwork/EpiGraphHub#33]
On CI forecast.sh script takes too long and 2h for the CI is not enough. Ignoring that, CI takes just 20 minutes.

Running it locally using a core i3, 4:20 hours was not enough to run half of the forecast calls (`make_forecast` and `make_forecast_all_cantons`).

it would be good to have a way to improve the performance of this script.

**Comment by fccoelho** [comment]
I think this can be closed, right @eduardocorrearaujo ?

**Comment by eduardocorrearaujo** [comment]
Yes.
