### ISSUE TITLE
get_colombia_data

### ISSUE THREAD

**Issue by eduardocorrearaujo** [thegraphnetwork/EpiGraphHub#34]
I'm working to get the Colombia data and by now it's almost 6 million lines. So, I'm getting the data from the API in chunks of 10000 records. 

To make this code faster, what you think it's better: 
- Get all the dataframe and so compare them to the data in the database using pangres to only save the new records or compare the data for each chunk of 10000 to the database to save the new records?

**Comment by fccoelho** [comment]
@eduardocorrearaujo  please create a draft PR with the code you already have.

**Comment by eduardocorrearaujo** [comment]
I put the script here: https://github.com/thegraphnetwork/EpiGraphHub/blob/get_colombia_data/Data_Collection/CRON_scripts/colombia_data.py
