### ISSUE TITLE
Add documentation to upload data using R

### ISSUE THREAD

**Issue by eduardocorrearaujo** [thegraphnetwork/EpiGraphHub#38]
It's necessary to add documentation to upload the data in R following the python example: https://github.com/thegraphnetwork/EpiGraphHub/blob/main/Documentation/datasources.md.

**Comment by dcpcamara** [comment]
Can you be a bit more clear, I did not understand exactly what should be done.

**Comment by dcpcamara** [comment]
@eduardocorrearaujo would you have schedule for a meeting to discuss this?

**Comment by eduardocorrearaujo** [comment]
Hi, Daniel, sorry for the time to answer. I have not seen your message before. I already solved this issue by adding an example to upload data to the database in this file: https://github.com/thegraphnetwork/EpiGraphHub/blob/main/Documentation/datasources.md

Take a look at this file and let me know if the section `using R` it's clear.

**Comment by xmnlab** [comment]
according to this comment: https://github.com/thegraphnetwork/EpiGraphHub/issues/38#issuecomment-1043005739
it seems it was already solved.
