### ISSUE TITLE
Instructions to name the tables in the database 

### ISSUE THREAD

**Issue by eduardocorrearaujo** [thegraphnetwork/EpiGraphHub#44]
It's necessary to create instructions to name the tables. It's essential to consider the following possibilities for the tables: 

- Table static or with update periodically;

- Result from an analysis (that can be used in a dashboard or report) or data used as input in the analysis;

- Table that contains the explanation of the columns of another table.

**Comment by fccoelho** [comment]
Proposed naming scheme:
all names should always be lower case.
Schema names:
Single country data: full ISO country name
global scale data: `global`

Table names: 
data tables:
`<locality>_<semantic single word name>_<0|D|W|M>_<optional suffix>`

`<>` symbols are just delimiters. On postgis tables representing maps, a `gis` prefix can be added.

The last portion should inform about the periodicity of the update. It should use D for daily, W for weekly, M for monthly and 0 for static.

Optional suffixes are: `meta` for metadata tables and `result` for analysis results

meta tables should be used to contain explanatory information about columns, it should contain at least these columns but can be enlarged to include other information available on existing data dictionaries for data that is imported into the system. 
```sql
table (
column_name varchar 128,
description text,
source text,
)
```

**Comment by dcpcamara** [comment]
If I want to name the table with the results from the Epinow model for Switzerland, it should be: 

> CH_epinowresults_D

 ?

**Comment by eduardocorrearaujo** [comment]
I think that should be: `CH_epinow_<option>_D_result`. In '<option>' I think that should be 'used cases', 'hosp' or 'rt' to better understand which curve the table is related to. What do you think, @fccoelho?

**Comment by eduardocorrearaujo** [comment]
> Proposed naming scheme: all names should always be lower case. Schema names: Single country data: full ISO country name global scale data: `global`
> 
> Table names: data tables: `<locality>_<semantic single word name>_<0|D|W|M>_<optional suffix>`
> 
> `<>` symbols are just delimiters. On postgis tables representing maps, a `gis` prefix can be added.
> 
> The last portion should inform about the periodicity of the update. It should use D for daily, W for weekly, M for monthly and 0 for static.
> 
> Optional suffixes are: `meta` for metadata tables and `result` for analysis results
> 
> meta tables should be used to contain explanatory information about columns, it should contain at least these columns but can be enlarged to include other information available on existing data dictionaries for data that is imported into the system.
> 
> ```sql
> table (
> column_name varchar 128,
> description text,
> source text,
> )
> ```

We should keep using the full name for the schemas or just the ISO code. For example, to create a schema for Brazilian data, I should name the schema as `Brazil` or `BRA`?  

Another thing that I think should be clear in the documentation is how to name the `<locality>`. If the data is for the entire country, I think that the ISO code should be used, but if the data is for a specific part of the country, how should we proceed? Should we put the entire name of the locality, o just an acronym? For example, If I upload some data from Paraná, Brazil, should I use in the `<locality>` the full name `Parana` or the acronym `PR` in the data base?

**Comment by xmnlab** [comment]
Would the table name be entirely lowercase? Based on one of firsts comments posted by @fccoelho , I understood that, but in the examples I sar some uppercases. Maybe I misunderstood it.

**Comment by eduardocorrearaujo** [comment]
I reread the Flavio comment, and you are right, Ivan. Thank you for noticing that. Another thing that I think is important is keeping all the column names in lowercase.

**Comment by xmnlab** [comment]
> Another thing that I think is important is keeping all the column names in lowercase.

sure thing :) 

Normally, for every name used for database (database, table, schema, field etc) or filesystem (file and folder) I use lowercase, without any special character or white space.

**Comment by fccoelho** [comment]
We have to be able to freeze snapshots of datasets, for example, to match published analyses to guarantee reproducibility.
I propose we use a `snapshots` schema for that, with the same name of the original table but with the string `YYYY_M_D` as  suffix. What do you think?

**Comment by fccoelho** [comment]
> Another thing that I think should be clear in the documentation is how to name the `<locality>`. If the data is for the entire country, I think that the ISO code should be used, but if the data is for a specific part of the country, how should we proceed? Should we put the entire name of the locality, o just an acronym? For example, If I upload some data from Paraná, Brazil, should I use in the `<locality>` the full name `Parana` or the acronym `PR` in the data base?

We should the standard used in GADM.org I think.

**Comment by eduardocorrearaujo** [comment]
> https://gadm.org/maps/BRA/parana_2.html
<img width="729" alt="Captura de Tela 2022-02-21 às 08 03 16" src="https://user-images.githubusercontent.com/65051489/154942871-21f0954f-3295-455e-943f-98837d286ac4.png">

So, should we use the values shown in the map id column or in the name column?

**Comment by fccoelho** [comment]
in the `name` column.

**Comment by fccoelho** [comment]
In order to close this issue, we need a volunteer to add these naming standards to the platform's documentation

**Comment by eduardocorrearaujo** [comment]
I can do this.
