### ISSUE TITLE
Spaces around names in colombia dataset

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#47]
As this query shows 
https://epigraphhub.org/superset/sqllab/?savedQueryId=7
the strings in `ciudad_municipio_nom` have spaces before them. 

This makes "correct" queries such as 
```sql
select * from casos_positivos_covid where ciudad_municipio_nom='ANTIOQUIA';
```
fail. To fix it we need to resort to pattern matching which is more costly. This is possibly true for other textual columns as well.

In order to fix, this we can either  reload  the entire  table and stripping the whitespaces before uploading the data, or use sql code such as this **!!! UNTESTED !!!**:
```sql
UPDATE casos_positivos_covid SET ciudad_municipio_nom=BTRIM(ciudad_municipio_nom);
```

**Comment by dcpcamara** [comment]
I would suggest a previous cleaning of all text variables to a standardized
pattern (such as lower_case, for instance). Then converting to a desired
pattern if one of such variables is used for linkage.

---------
*Daniel C. P. Câmara, PhD.*

*Laboratório de Mosquitos Transmissores de Hematozoários - LATHEMA, Fiocruz*
*Núcleo** Operacional Sentinela de Mosquitos Vetores - NOSMOVE, Fiocruz*
*Incident Management Support Team - IMST, WHO Afro*

*The GRAPH Network, UNIGE*
*Rio de Janeiro, Brasil*


Em seg., 21 de fev. de 2022 às 12:33, Flávio Codeço Coelho <
***@***.***> escreveu:

**Comment by eduardocorrearaujo** [comment]
I think it's better to reload all the dataset. Since a routine to remove these spaces will need to be incorporated in the scripts to get this data to avoid errors in the future. Do you want that I change upper characters to lower characters too?

**Comment by fccoelho** [comment]
for the data (city names, etc) it is not necessary to change the case. It's recommended to leave it as close to the original as possible.
