### ISSUE TITLE
Create a Deployment for KoBoToolbox

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#54]
We need to run an instance of KoboToolBox to support our field data collection.
Fortunately it is already very simple to deploy as it is completely containerized.

https://github.com/kobotoolbox/kobo-install

All we need is to automate the management of the instances with Ansible and setup a subdomain for it. For example kobo.epigraphhub.org

**Comment by dcpcamara** [comment]
I believe we can do this very easily via R and using their API (
https://kc.kobotoolbox.org/api/v1/). Do we have the forms and privileges (a
user login and pass) to download and start working on it?

---------
*Daniel C. P. Câmara, PhD.*

*Laboratório de Mosquitos Transmissores de Hematozoários - LATHEMA, Fiocruz*
*Núcleo** Operacional Sentinela de Mosquitos Vetores - NOSMOVE, Fiocruz*
*Incident Management Support Team - IMST, WHO Afro*

*The GRAPH Network, UNIGE*
*Rio de Janeiro, Brasil*


Em sex., 4 de mar. de 2022 às 13:09, Flávio Codeço Coelho <
***@***.***> escreveu:

**Comment by fccoelho** [comment]
We first have to complete this issue, which is to actually get KoBoToolbox running on our server.  Then we can create the users and use the APIs.
I have already deployed it on my laptop in a little more than 5 minutes, so @xmnlab should be able to have it deployed on our server very  soon

**Comment by xmnlab** [comment]
I am trying to install it for "server" but it is failing because it is trying to use the same port of the current nginx. 
I am investigating the problem. any recommendation?

**Comment by xmnlab** [comment]
I am taking a look into this approach: https://github.com/kobotoolbox/kobo-install/issues/54

**Comment by fccoelho** [comment]
Here was the same thing. It has it's own web server container that listens at port 80. According to the README  the advanced options let's you pick a different port, I haven't tried to fiddle with the advanced options.

**Comment by xmnlab** [comment]
it seems that the configuration for ports is just for workstation (not server).
For server, we need to use something like this: https://github.com/kobotoolbox/kobo-install/issues/54

```
Is `KoBoToolbox` behind a reverse-proxy/load-balancer?
    1) Yes
    2) No
[1]: 
Is your reverse-proxy/load-balancer installed on this server?
    1) Yes
    2) No
[1]: 
Internal port used by reverse proxy?
[8080]: 80
Ports 80 and 443 are reserved!
[80]: 8080
```

I tried, but it didn´t work well. it is waiting for some result for a long time .. but never worked (until my ssh session disconeect).

I need to investigate it more.

**Comment by xmnlab** [comment]
server is up and running :)
https://kobo.epigraphhub.org/

is there anything else for this issue? or could it be closed?

**Comment by dcpcamara** [comment]
Congratulations, my friend!

**Comment by xmnlab** [comment]
the smtp service is already working.

for now, it is ready for testing. 
maybe we can establish some time for testing and we can release it officially for production.
