### ISSUE TITLE
Improve the template of the login page

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#62]
We need to make the EpigraphHUb login page more interesting and informative. 

One Idea is to add some screenshots and text with an ovrview of the features  of the tool. We can use the [Supeset home page](https://superset.apache.org/) as inspiration.

The template for the page is this: https://github.com/thegraphnetwork/EpiGraphHub/blob/main/docker/superset/public_welcome.html
The template is a jinja2 tempate, so care must be taken not to override the template tags. The page's content is what is inside the `{% content %}` block which currently looks like this:

```jinja2
{% block content %}
<h2><center>Welcome to EpigraphHub</center></h2>
<p>
  If you just want to browse the published dashboards and charts, 
  please login with the <b>guest</b> account! password: guest.
</p>
{% endblock %}
```

Based on I what I have foun in  other templates you can apply Bootstrap CSS classes to help with the layout. See [here](https://github.com/apache/superset/blob/9773aba522e957ed9423045ca153219638a85d2f/superset/templates/superset/theme.html) for example.

**Comment by kendavidn** [comment]
Hello! Recently was recommended this site: https://beefree.io/ for building simple single-HTML-page sites. 

You build with a drag-and-drop interface. Then you can export as a single, lightweight HTML page (images hosted online). It's free for basic features, with many good templates. Good resizing (mobile-responsive) behavior for all the templates. There is no fancy javascript or anything like that. So I imagine the superset homepage container should handle it well. 

As a quick demo:
-	I took this template https://beefree.io/template/multi-purpose-business/
-  and modified it to this: https://singular-praline-4c2df4.netlify.app/
-  with the code here: https://gist.github.com/kendavidn/7f35e41fc74b9d8bba193f9f1d94d1fb

**Comment by kendavidn** [comment]
<img width="485" alt="CleanShot 2022-04-16 at 13 45 29@2x" src="https://user-images.githubusercontent.com/71232724/163673653-c458907b-a285-40e5-922c-e5396240113e.png">

**Comment by fccoelho** [comment]
Thanks @kendavidn ! 

I'll make sure to use some of these Ideas, but I'll  try to add some extra info for newcomers! Such as links for the documentation, libraries, etc!
