### ISSUE TITLE
Query from Google sheet not working

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#65]
This is the eror message:

```python
Google Sheets Error

Can't load plugin: sqlalchemy.dialects:gsheets
```

I remember on the old deploy I had to manually install the google sheets plugin for  sqlalchemy:
https://superset.apache.org/docs/databases/google-sheets

**Comment by xmnlab** [comment]
it seems that there is some problem with `enum34`:

> epigraphhub_1     | [SupersetError(message="The 'enum34' distribution was not found and is required by the application", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Google Sheets', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
epigraphhub_1     | 2022-03-24 03:44:31,144:WARNING:superset.views.base:[SupersetError(message="The 'enum34' distribution was not found and is required by the application", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Google Sheets', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]


enum34 was installed, so not sure about this problem. I will investigate this problem

**Comment by fccoelho** [comment]
Didi you install `Shillelagh`?

**Comment by xmnlab** [comment]
oh nop, I will try that.

sorry, I was confused because in the link you shared, there is another link to https://preset.io/blog/2020-06-01-connect-superset-google-sheets/

and there they are using: `gsheetsdb`

**Comment by fccoelho** [comment]
Right, but I think that currently they are using Shillelagh for that

**Comment by fccoelho** [comment]
My old friend Beto de Almeida is the author of this library.

**Comment by xmnlab** [comment]
> Unable to load dialect <class 'sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi'>: type object 'MSDialect_adodbapi' has no attribute 'dbapi'
epigraphhub_1 | 2022-03-24 13:25:57,637:WARNING:superset.db_engine_specs:Unable to load dialect <class 'sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi'>: type object 'MSDialect_adodbapi' has no attribute 'dbapi'

maybe related: https://github.com/apache/superset/issues/19109
