### ISSUE TITLE
Information in the metadata tables

### ISSUE THREAD

**Issue by eduardocorrearaujo** [thegraphnetwork/EpiGraphHub#68]
In the issue #44 was defined that the metadata tables should have at least the following information: 

```
table (
column_name varchar 128,
description text,
source text,
)

```

I was wondering about a way to introduce also in this data a brief description of the content of the table. What do you think about it? 

In this case, I was thinking about adding in the `collum_name` column the term `dataset` and fill the description in the `description` column.

**Comment by xmnlab** [comment]
I am not super aware of this effort. But, if it will improve the data structure, i don't have any objection :)

**Comment by eduardocorrearaujo** [comment]
Great! 

I have another question, @fccoelho and @dcpcamara. 
How should we define the source for the datasets with results, like the table with the forecasts and nowcast results? How we did this analysis in the source column do I should put `epigraphhub`?

**Comment by fccoelho** [comment]
In this case, We can cite the code used for the analysis, maybe with the github link.
