### ISSUE TITLE
Problem asynchronous queries

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#70]
Superset allows asynchronous queries through celery.

Since the move to the Docker deployment, asynchronous queries seem to have stopped working.

Maybe it has to do with the URI of the REDIS broker, which is currently set to localhost (is this right?)

maybe e can install flower to check if the tasks are being scheduled

**Comment by fccoelho** [comment]
I disabled asynchronous query execution on the databases for now, but they are needed for queries that are longer than the timeout limit for the http request

**Comment by xmnlab** [comment]
> Maybe it has to do with the URI of the REDIS broker, which is currently set to localhost (is this right?)

I think that it should work, because currently the epgh container is running with network in host mode.

**Comment by xmnlab** [comment]
I enabled the option again to check the log:

> 51b34dae6227_docker_epigraphhub_1 | /opt/conda/envs/epigraphhub/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py:661: SAWarning: Dialect sqlite+pysqlite does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
51b34dae6227_docker_epigraphhub_1 |   util.warn(
51b34dae6227_docker_epigraphhub_1 | Triggering query_id: 548
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:22,721:INFO:superset.sqllab.command:Triggering query_id: 548
51b34dae6227_docker_epigraphhub_1 | SQLite Database support for metadata databases will be removed             in a future version of Superset.
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:22,755:WARNING:superset.utils.celery:SQLite Database support for metadata databases will be removed             in a future version of Superset.
51b34dae6227_docker_epigraphhub_1 | Query 548: Executing 1 statement(s)
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:22,796:INFO:superset.sql_lab:Query 548: Executing 1 statement(s)
51b34dae6227_docker_epigraphhub_1 | Query 548: Set query to 'running'
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:22,796:INFO:superset.sql_lab:Query 548: Set query to 'running'
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:22,852:INFO:werkzeug:135.181.41.20 - - [06/Apr/2022 22:44:22] "GET /api/v1/dataset?q=%28filters%3A%21%28%28col%3Atable_name%2Copr%3Act%2Cvalue%3A%27%27%29%2C%28col%3Aowners%2Copr%3Arel_m_m%2Cvalue%3A11%29%29%2Corder_column%3Achanged_on_delta_humanized%2Corder_direction%3Adesc%29 HTTP/1.0" 308 -
51b34dae6227_docker_epigraphhub_1 | Query 548: Running statement 1 out of 1
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:22,861:INFO:superset.sql_lab:Query 548: Running statement 1 out of 1
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:23,039:INFO:werkzeug:135.181.41.20 - - [06/Apr/2022 22:44:23] "GET /superset/queries/1649285039761 HTTP/1.0" 200 -
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:23,129:INFO:werkzeug:135.181.41.20 - - [06/Apr/2022 22:44:23] "POST /superset/sql_json/ HTTP/1.0" 200 -
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:23,339:INFO:werkzeug:135.181.41.20 - - [06/Apr/2022 22:44:23] "GET /static/assets/d36caa7e430c7b303adb.chunk.js HTTP/1.0" 200 -
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:30,500:INFO:werkzeug:127.0.0.1 - - [06/Apr/2022 22:44:30] "GET /health HTTP/1.1" 200 -
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:48,915:INFO:werkzeug:135.181.41.20 - - [06/Apr/2022 22:44:48] "GET /superset/extra_table_metadata/2/caso_full/brasil/ HTTP/1.0" 200 -
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:49,317:INFO:werkzeug:135.181.41.20 - - [06/Apr/2022 22:44:49] "GET /api/v1/database/2/table/caso_full/brasil/ HTTP/1.0" 200 -
51b34dae6227_docker_epigraphhub_1 | Triggering query_id: 549
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:49,712:INFO:superset.sqllab.command:Triggering query_id: 549
51b34dae6227_docker_epigraphhub_1 | SQLite Database support for metadata databases will be removed             in a future version of Superset.
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:49,733:WARNING:superset.utils.celery:SQLite Database support for metadata databases will be removed             in a future version of Superset.
51b34dae6227_docker_epigraphhub_1 | Query 549: Executing 1 statement(s)
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:49,771:INFO:superset.sql_lab:Query 549: Executing 1 statement(s)
51b34dae6227_docker_epigraphhub_1 | Query 549: Set query to 'running'
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:49,772:INFO:superset.sql_lab:Query 549: Set query to 'running'
51b34dae6227_docker_epigraphhub_1 | Query 549: Running statement 1 out of 1
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:49,830:INFO:superset.sql_lab:Query 549: Running statement 1 out of 1
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:50,015:INFO:werkzeug:135.181.41.20 - - [06/Apr/2022 22:44:50] "POST /superset/sql_json/ HTTP/1.0" 200 -
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:44:50,599:INFO:werkzeug:127.0.0.1 - - [06/Apr/2022 22:44:50] "GET /health HTTP/1.1" 200 -
51b34dae6227_docker_epigraphhub_1 | Triggering query_id: 550
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:45:08,606:INFO:superset.sqllab.command:Triggering query_id: 550
51b34dae6227_docker_epigraphhub_1 | Query 550: Running query on a Celery worker
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:45:08,617:INFO:superset.sqllab.sql_json_executer:Query 550: Running query on a Celery worker
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:45:08,684:INFO:werkzeug:135.181.41.20 - - [06/Apr/2022 22:45:08] "POST /superset/sql_json/ HTTP/1.0" 202 -
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:45:08,986:INFO:werkzeug:135.181.41.20 - - [06/Apr/2022 22:45:08] "GET /superset/queries/1649285057861.978 HTTP/1.0" 200 -
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:45:10,733:INFO:werkzeug:127.0.0.1 - - [06/Apr/2022 22:45:10] "GET /health HTTP/1.1" 200 -

It shows that celery is running:

> 1b34dae6227_docker_epigraphhub_1 | Query 550: Running query on a Celery worker
51b34dae6227_docker_epigraphhub_1 | 2022-04-06 22:45:08,617:INFO:superset.sqllab.sql_json_executer:Query 550: Running query on a Celery worker

after a lot of minutes, I tried to cancel the execution and it raised an error:

> 51b34dae6227_docker_epigraphhub_1 | Could not cancel query
51b34dae6227_docker_epigraphhub_1 | Traceback (most recent call last):
51b34dae6227_docker_epigraphhub_1 |   File "/opt/conda/envs/epigraphhub/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
51b34dae6227_docker_epigraphhub_1 |     rv = self.dispatch_request()
51b34dae6227_docker_epigraphhub_1 |   File "/opt/conda/envs/epigraphhub/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
51b34dae6227_docker_epigraphhub_1 |     return self.view_functions[rule.endpoint](**req.view_args)
51b34dae6227_docker_epigraphhub_1 |   File "/opt/conda/envs/epigraphhub/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 190, in wraps
51b34dae6227_docker_epigraphhub_1 |     return f(self, *args, **kwargs)
51b34dae6227_docker_epigraphhub_1 |   File "/opt/conda/envs/epigraphhub/lib/python3.8/site-packages/superset/utils/log.py", line 242, in wrapper
51b34dae6227_docker_epigraphhub_1 |     value = f(*args, **kwargs)
51b34dae6227_docker_epigraphhub_1 |   File "/opt/conda/envs/epigraphhub/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
51b34dae6227_docker_epigraphhub_1 |     ret = target(*args, **kwargs)
51b34dae6227_docker_epigraphhub_1 |   File "/opt/conda/envs/epigraphhub/lib/python3.8/site-packages/superset/views/core.py", line 2364, in stop_query
51b34dae6227_docker_epigraphhub_1 |     raise SupersetCancelQueryException("Could not cancel query")


I will continue investigating the problem

**Comment by fccoelho** [comment]
@xmnlab what's the status here?

**Comment by xmnlab** [comment]
I hope to have it fixed by https://github.com/thegraphnetwork/EpiGraphHub/pull/83

the service is already working, now I need to check the async method there.

**Comment by fccoelho** [comment]
@xmnlab can we close this one?

**Comment by xmnlab** [comment]
This is already working on production :)
