### ISSUE TITLE
Add an Airflow container to our platform 

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#72]
In order to start to test the migration of the data-collection tasks to apache-airflow we need and instance of airflow running that we can submit workflow DAGs to.

Here is the relevant documentation. 
https://airflow.apache.org/docs/apache-airflow/stable/installation/index.html#using-production-docker-images

**Comment by xmnlab** [comment]
nice! I will take a look into that.
